// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiTenancyDemo.Data;

namespace MultiTenancyDemo.Migrations
{
    [DbContext(typeof(MultiTenancyDbContext))]
    partial class MultiTenancyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MultiTenancyDemo.Data.Goods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("Status");

                    b.Property<int>("TenancyId");

                    b.Property<int?>("TenantInfoId");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("TenantInfoId");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("MultiTenancyDemo.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OrderDes");

                    b.Property<int>("TenancyId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TenancyId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("MultiTenancyDemo.Data.TenantInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Connection");

                    b.Property<string>("Name");

                    b.Property<int>("TenantDbType");

                    b.Property<int>("TenantType");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("TenantInfo");
                });

            modelBuilder.Entity("MultiTenancyDemo.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<int>("TenancyId");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("TenancyId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("MultiTenancyDemo.Data.Goods", b =>
                {
                    b.HasOne("MultiTenancyDemo.Data.TenantInfo", "TenantInfo")
                        .WithMany()
                        .HasForeignKey("TenantInfoId");
                });

            modelBuilder.Entity("MultiTenancyDemo.Data.Order", b =>
                {
                    b.HasOne("MultiTenancyDemo.Data.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MultiTenancyDemo.Data.User", b =>
                {
                    b.HasOne("MultiTenancyDemo.Data.TenantInfo", "TenantInfo")
                        .WithOne("User")
                        .HasForeignKey("MultiTenancyDemo.Data.User", "TenancyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
